In [1]:
pip install sklearn-genetic

Requirement already satisfied: sklearn-genetic in c:\users\compumarts\anaconda3\envs\gpu2\lib\site-packages (0.6.0)
Requirement already satisfied: scikit-learn>=1.0 in c:\users\compumarts\anaconda3\envs\gpu2\lib\site-packages (from sklearn-genetic) (1.4.2)
Requirement already satisfied: deap>=1.0.2 in c:\users\compumarts\anaconda3\envs\gpu2\lib\site-packages (from sklearn-genetic) (1.4.1)
Requirement already satisfied: numpy in c:\users\compumarts\anaconda3\envs\gpu2\lib\site-packages (from sklearn-genetic) (1.26.3)
Requirement already satisfied: multiprocess in c:\users\compumarts\anaconda3\envs\gpu2\lib\site-packages (from sklearn-genetic) (0.70.16)
Requirement already satisfied: scipy>=1.6.0 in c:\users\compumarts\anaconda3\envs\gpu2\lib\site-packages (from scikit-learn>=1.0->sklearn-genetic) (1.13.0)
Requirement already satisfied: joblib>=1.2.0 in c:\users\compumarts\anaconda3\envs\gpu2\lib\site-packages (from scikit-learn>=1.0->sklearn-genetic) (1.4.2)
Requirement already satisfied: threadpoolctl>=2.0.0 in c:\users\compumarts\anaconda3\envs\gpu2\lib\site-packages (from scikit-learn>=1.0->sklearn-genetic) (3.5.0)
Requirement already satisfied: dill>=0.3.8 in c:\users\compumarts\anaconda3\envs\gpu2\lib\site-packages (from multiprocess->sklearn-genetic) (0.3.8)
Note: you may need to restart the kernel to use updated packages.

In [4]:
import pandas as pd 
from genetic_selection import GeneticSelectionCV
from sklearn.ensemble import RandomForestClassifier

In [5]:
df= pd.read_csv("chronic-kidney_clean.csv")
df.head()

,age,bp,sg,al,su,rbc,pc,pcc,ba,bgr,...,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
0,48,80,1.020,1,0,0,0,0,0,121,...,44,7800,5.2,1,1,0,0,0,0,ckd
1,7,50,1.020,4,0,0,0,0,0,121,...,38,6000,4.8,0,0,0,0,0,0,ckd
2,62,80,1.010,2,3,0,0,0,0,423,...,31,7500,4.8,0,1,0,1,0,1,ckd
3,48,70,1.005,4,0,0,1,1,0,117,...,32,6700,3.9,1,0,0,1,1,1,ckd
4,51,80,1.010,2,0,0,0,0,0,106,...,35,7300,4.6,0,0,0,0,0,0,ckd

In [6]:
X=df.drop(['classification'],axis = 1 )
y=df['classification']
feature_names=X.columns

In [ ]:
estimator = RandomForestClassifier(max_depth=10, random_state=0)
model = GeneticSelectionCV(
    estimator, cv=2, verbose=0,
    scoring="accuracy", max_features=7,
    n_population=100, crossover_proba=0.5,
    mutation_proba=0.2, n_generations=50,
    crossover_independent_proba=0.5,
    mutation_independent_proba=0.04,
    tournament_size=3, n_gen_no_change=10,
    caching=True, n_jobs=-1)
model = model.fit(X, y)
print('Features:', X.columns[model.support_])